### ISSUE TITLE
iframe height auto

### ISSUE THREAD

**Issue by luwes** [jgthms/minireset.css#18]
Not 100% sure it's an issue but when I upgraded Bulma some of the social iframe buttons had too big of an height. See screenshot. If the `height: auto` is toggled off the Github button returned to its normal height.

<img width="1256" alt="screen shot 2019-02-10 at 8 24 54 am" src="https://user-images.githubusercontent.com/360826/52534281-a3f3cf00-2d0d-11e9-8468-121d85cb40f6.png">

Link: https://swiss-element.netlify.com/

**Comment by cve** [comment]
How did you fixed it?

**Comment by georgfranz** [comment]
Hi,

I've problems with ads which are displayed within an iframe. The iframe is only taking about one-third of the height it should, so the ad is not displayed fully. 

The reason is the mini reset of the iframe to height auto

I've added 

.my-ad-container iframe
{
height: 100%;
}

to avoid the problem.

Best wishes,
Georg.

**Comment by tjkohli** [comment]
This caused me so much grief as I just spent 6 hours tracing it down to this issue. I'm glad this horrible line of CSS has been removed in `0.0.5`.

**Comment by FabianRohr** [comment]
@tjkohli Im on the latest Bulma version 0.7.5 and the line has not been removed. I don't have a working solution to this.

**Comment by itwasmattgregg** [comment]
I'm wondering why this line is in there. It's not actually a part of reset.css originally.
